name: GitHub Pages Publish

on:
  workflow_call:
    inputs:
      semvertag:
        required: true
        type: string
      folder:
        required: false
        type: string
        default: 'build/html'
  workflow_dispatch:
    inputs:
      semvertag:
        required: true
        type: string
      folder:
        required: false
        type: string
        default: 'build/html'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: docs
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: config
        run: |
          cmake -S. -Bbuild
      - name: build
        run: cmake --build build
      - name: test
        run: ctest --test-dir build -C Debug -V
      - name: Doc tasks
        uses: mattnotmitt/doxygen-action@v1
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ inputs.folder }}
          target-folder: ${{ inputs.semvertag }}