name: Unit CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: config
        run: |
          cmake -S. -Bbuild
      - name: build
        run: cmake --build build
      - name: test
        run: ctest --test-dir build -build-config Release -V


